// <auto-generated />
using System;
using DataAcces;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAcces.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230921220024_created_Date")]
    partial class created_Date
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Database.DbUser", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Uid");

                    b.Property<bool>("AccountActive")
                        .HasColumnType("bit")
                        .HasColumnName("Account_Active");

                    b.Property<bool>("AccountLockedOut")
                        .HasColumnType("bit")
                        .HasColumnName("Account_Locked_Out");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Created_Date");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("Email_Confirmed");

                    b.Property<DateTime?>("FailedTimoutTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Failed_Timout_Time");

                    b.Property<int>("LoginFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("Login_Failed_Count");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Phone_Number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("Phone_Number_Confirmed");

                    b.Property<bool>("TwoFactorAuthenticationEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("Two_Factor_Authentication_Enabled");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Username");

                    b.HasKey("Uid");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Uid"));

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
